### ISSUE TITLE
Parser Error: Native class "EditorPlugin" cannot be constructed as it is abstract.

### ISSUE THREAD

**Issue by Geams** [NitroxNova/humanizer#21]
When trying to run `authoring.tscn` this error pops up:
`Parser Error: Native class "EditorPlugin" cannot be constructed as it is abstract.`
`func create_import_settings():
  var import_text = FileAccess.open("res://addons/humanizer/data/animations/import_settings.txt", FileAccess.READ).get_as_text()
**var ep = EditorPlugin.new()**
	for file_name in OSPath.get_files(input_folder):`

I am using version v1.2.0.beta
I installed FBX2glTF and set `filesystem/import/fbx/enabled`

**Comment by NitroxNova** [comment]
correct you cannot run the authoring scene, it is only an editor tool meant for pregenerating characters, if you need an in-game creator you can check out my example menu: https://github.com/NitroxNova/Humanizer_Example

**Comment by Geams** [comment]
Thanks for your reply, I did that but what is the humanizer global scene?
`**Important** drag the global_config_override.res into the humanizer global scene and save, otherwise it will throw an error that it cant find the clothes   `

**Comment by NitroxNova** [comment]
you still dont run the authoring scene, ever. the authoring scene is only used in the editor. if you have the example menu set up, then hit the play button (or run the new_character_menu.tscn) it will open the character scene. if you have more issues with the ingame menu please leave an issue on that repo thanks. you understand that everyone will have different requirements for their in game menu, so i cant just distribute one, you use the plugin to build it? its complicated because its free, and in beta. if its still too much effort for you feel free to use unity's UMA or unreal's MetaHuman
