### ISSUE TITLE
Invalid get index `default_baked_root_node` (on base: `Nil`).

### ISSUE THREAD

**Issue by sagersmith8** [NitroxNova/Humanizer#6]
### Description
```
Invalid get index `default_baked_root_node` (on base: `Nil`).
```

on line 105 of humanizer.gd

```
@export_enum("CharacterBody3D", "RigidBody3D", "StaticBody3D", "Area3D") var _baked_root_node: String = HumanizerGlobalConfig.config.default_baked_root_node
```

I assume this is because I haven't configured my `HumanizerGlobalConfig.config` but its not currently clear how I'm meant to configure it. I am attempting to view the `Humanizer` in a scene and view it through a camera to make an in game Character creator

**Comment by matt-seaton** [comment]
If this did not resolve your issue please let us know.  I'm going to mark it as closed for now

**Comment by sagersmith8** [comment]
You fixed it for me! Thanks @matt-seaton, this project is very cool!

**Comment by sagersmith8** [comment]
In a real game you said you wouldn't load the Humanizer node, is there something better for me to be loading? I am trying to use it as an in game character creator


![Screenshot 2024-04-24 at 8 54 41 PM](https://github.com/NitroxNova/Humanizer/assets/10541522/76b35f5c-7999-4e20-b7c2-8f13c802eb3d)

**Comment by matt-seaton** [comment]
In a character creator you absolutely would load the humanizer node.  That is the correct thing to do.

What I meant was you wouldn't load it immediately as the entry point of the game.  Presumably you would load a main menu first before your character creator.

In that case there wouldn't be this race condition for the singleton to enter the tree before the humanizer node loads because by the time you load the humanizer node later on the singleton will already have been there for some time.

**Comment by sagersmith8** [comment]
OHHHH, okay yeah, cool, we are on the same page.
